language: cpp
compiler:
  - gcc
  - clang
# Change this to your needs
script: make

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libboost-all-dev google-mock cmake
 - cd /usr/src/gtest&&sudo cmake&&sudo make&&sudo mv libg* /usr/lib
